Vagrant.configure("2") do |config|
  config.vm.box = "UbuntuServer16"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox"

  config.vm.define "kube-node1" do |node|
    node.vm.network "forwarded_port", guest: 6443, host: 6443 # kube-apiserver
    node.vm.network "forwarded_port", guest: 32666, host: 32666 # kube-dashboard
    node.vm.provision "config-normal", type: "shell", path: "config-normal.sh", args:"1"
    node.vm.network :private_network, ip: "172.27.129.11",  auto_config: true
    node.vm.hostname = "kube-node1"
    node.vm.provider :virtualbox do |vb, override|
      vb.name = "kube-node1"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "kube-node2" do |node|
    node.vm.provision "config-normal", type: "shell", path: "config-normal.sh", args:"2"
    node.vm.network :private_network, ip: "172.27.129.12",  auto_config: true
    node.vm.hostname = "kube-node2"
    node.vm.provider :virtualbox do |vb, override|
      vb.name = "kube-node2"
      vb.gui = false
      vb.memory = 6144
      vb.cpus = 3
    end
  end

  config.vm.define "kube-node3" do |node|
    node.vm.provision "config-normal", type: "shell", path: "config-normal.sh", args:"3"
    node.vm.network :private_network, ip: "172.27.129.13",  auto_config: true
    node.vm.hostname = "kube-node3"
    node.vm.provider :virtualbox do |vb, override|
      vb.name = "kube-node3"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 1
    end
  end

end
